# Generated by Django 5.2.6 on 2025-10-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('published', 'Published')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
