# Generated by Django 5.2.6 on 2025-10-10 04:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_images/ubxxfzpnrezvtqerdigw', max_length=255, null=True, verbose_name='image'),
        ),
    ]
