# Generated by Django 5.2.6 on 2025-10-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='article_images/breaking.webp', null=True, upload_to='article_images/'),
        ),
    ]
