# Generated by Django 5.2.6 on 2025-12-28 07:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_article_image.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
